config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
  end

  resources :event_params
  resources :categories

   get 'history', to: 'history#index'

  root 'home#index', as: :home
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_events = Event.order(created_at: :desc).limit(5)
    @categories = Category.includes(:events)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="title_container">
<h1>Дешборд</h1>

<div>
  <%= link_to 'Події', events_path, class: 'btn btn-custom-color' %>
  <%= link_to 'Параметри Подій', event_params_path, class: 'btn btn-custom-color' %>
  <%= link_to 'Категорії', categories_path, class: 'btn btn-custom-color' %>
</div>
</div>

<div class="dashboard">
  <div class="latest-events">
    <h2>Останні події</h2>
    <ul>
      <% @latest_events.each do |event| %>
        <li>
          <strong><%= link_to event.name, event_path(event), class:'btn-link' %></strong>
          <p><%= event.description %></p>
          <p><strong>Категорія:</strong> <%= event.category.name %></p>
          <p><strong>Створено:</strong> <%= event.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
        </li>
      <% end %>
    </ul>
    <%= link_to 'Усі події', events_path, class: 'btn btn-link' %>
  </div>

  <div class="categories-stats">
    <h2>Статистика</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Категорія</th>
          <th>iOS Впроваджено %</th>
          <th>iOS Випуск %</th>
          <th>Android Впроваджено %</th>
          <th>Android Випуск %</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= percentage(category.events.where.not(ios_impl: nil).count, category.events.count) %>%</td>
            <td><%= percentage(category.events.where.not(ios_release: nil).count, category.events.count) %>%</td>
            <td><%= percentage(category.events.where.not(android_impl: nil).count, category.events.count) %>%</td>
            <td><%= percentage(category.events.where.not(android_release: nil).count, category.events.count) %>%</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>