config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
  end

  resources :event_params
  resources :categories

   get 'history', to: 'history#index'

  root 'home#index', as: :home
end

app/models/event.rb
class Event < ApplicationRecord
  include ActiveModel::Serializers::JSON
  
  belongs_to :category
  has_and_belongs_to_many :event_params
  has_many_attached :attachments
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  has_paper_trail

  def to_s
    name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
  
    def index
      @events = Event.all
  
      if params[:search].present?
        @events = @events.where('name LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
      end
    end
  
    def show
      @comment = Comment.new
    end
  
    def new
      @event = Event.new
      @event_params = EventParam.all
    end
  
    def edit
      @event_params = EventParam.all
    end
  
    def create
      handle_category
      handle_event_params
  
      @event = Event.new(db_only_params.merge(category_id: @category.id, event_param_ids: @event_param_ids))
  
      if @event.save
        redirect_to @event, notice: 'Event was successfully created.'
      else
        flash.now[:alert] = 'There was an error creating the event. Please check the form for details.'
        @event_params = EventParam.all
        render :new
      end
    end
  
    def update
      handle_category
      handle_event_params

      update_params = db_only_params
      update_params[:event_param_ids] = @event_param_ids if @event_param_ids.present?
      update_params[:category_id] = @category.id if @category.present?

      if @event.update(update_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        @event_params = EventParam.all
        flash.now[:alert] = 'There was an error updating the event. Please check the form for details.'
        render :edit
      end
    end
  
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    end
  
    private
  
    def set_event
      @event = Event.find(params[:id])
    end
  
    def custom_params
      params.require(:event).permit(
        :name,
        :description,
        :category_id,
        :ios_impl,
        :android_impl,
        :ios_release,
        :android_release,
        :new_category,
        new_event_params: [],
        event_param_ids: [],
        attachments: []
      )
    end

    def db_only_params
      custom_params.except(:new_category, :new_event_params)
    end

    def handle_category
        if custom_params[:new_category].present?
            @category = Category.find_or_create_by(name: custom_params[:new_category])
        elsif custom_params[:category_id].present?
            @category = Category.find(custom_params[:category_id])
        else
        end
    end
  
    def handle_event_params
      @event_param_ids = custom_params[:event_param_ids] || []
  
      if custom_params[:new_event_params].present?
        custom_params[:new_event_params].each do |param_name|
          next if param_name.blank?
  
          new_param = EventParam.find_or_create_by(name: param_name)
          @event_param_ids << new_param.id if new_param.persisted?
        end
      end
    end
  end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_table.html.erb
<% events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td class="description-cell">
      <input type="checkbox" id="toggle-description-<%= event.id %>" />
      <label for="toggle-description-<%= event.id %>" class="show-more-label"></label>
      <span class="short-description">
        <%= truncate(event.description, length: 200) %>
      </span>
      <span class="full-description">
        <%= event.description %>
      </span>
    </td>
    <td><%= event.category.name %></td>
    <td>
      <% if event.ios_impl.present? %>
        <i class="fab fa-apple"></i> <%= event.ios_impl.strftime("%Y-%m-%d %H:%M") %><br>
      <% end %>
      <% if event.android_impl.present? %>
        <i class="fab fa-android"></i> <%= event.android_impl.strftime("%Y-%m-%d %H:%M") %><br>
      <% end %>
    </td>
    <td>
      <% if event.ios_release.present? %>
        <i class="fab fa-apple"></i> <%= event.ios_release.strftime("%Y-%m-%d %H:%M") %><br>
      <% end %>
      <% if event.android_release.present? %>
        <i class="fab fa-android"></i> <%= event.android_release.strftime("%Y-%m-%d %H:%M") %><br>
      <% end %>
    </td>
    <td>
      <%= link_to '🔍', event, class: 'btn btn-custom-color btn-sm', title: 'Показати' %>
      <% if current_user.can_open_event_edit? %>
        <%= link_to '✏️', edit_event_path(event), class: 'btn btn-custom-color btn-sm', title: 'Редагувати' %>
      <% end %>
      <% if current_user.can_delete_event? %>
        <%= link_to '🗑️', event_path(event), data: { turbo_method: :delete, turbo_confirm: 'Ви впевнені?' }, class: 'btn btn-custom-color btn-sm', title: 'Видалити' %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, html: { multipart: true, class: 'form_container' }) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prevented this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%if current_user.can_edit_event? %>
  <div class="form-group">
    <%= form.label :name, "Ім'я" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Опис" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group" data-controller="category">
    <%= form.label :category_id, "Категорія" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: 'Оберіть існуючу категорію' }, { class: 'form-control', id: 'event_category_id', data: { category_target: 'categorySelect' } } %>
    <br>
    <label>
      <input type="checkbox" id="new_category_checkbox" data-category-target="newCategoryCheckbox" data-action="category#toggle"> Або створіть нову категорію
    </label>
    <%= form.text_field :new_category, class: 'form-control', id: 'new_category_input', placeholder: 'Назва', style: 'display:none;', data: { category_target: 'newCategoryInput' } %>
  </div>

  <div class="form-group" data-controller="event-params">
    <%= form.label :event_params, "Параметри події" %>
    <%= form.collection_select :event_param_ids, @event_params, :id, :name, {}, { multiple: true, class: 'form-control', id: 'event_param_ids', data: { event_params_target: 'eventParamsSelect' } } %>
    
    <div id="new-event-params">
      <label>
        <input type="checkbox" id="add_new_event_param_checkbox" data-event-params-target="addNewEventParamCheckbox" data-action="event-params#toggle"> Або створіть новий параметр
      </label>
      
      <!-- Hidden container for dynamic inputs -->
      <div id="new-event-params-container" style="display:none;" data-event-params-target="newEventParamsContainer">
        <!-- Ensure that input names end with [] to be treated as an array -->
        <div class="input-group mb-3">
          <input type="text" name="event[new_event_params][]" class="form-control" placeholder="Назва параметра">
          <button type="button" class="btn btn-danger" data-action="click->event-params#removeInput">Видалити</button>
        </div>
      </div>

      <button type="button" class="btn btn-secondary" data-event-params-target="addInputButton" data-action="click->event-params#addInput" style="display:none;">Додати параметр</button>
    </div>
  </div>

  <div class="form-group">  
    <%= form.label :attachments, "Вкладення" %>
    <%= form.file_field :attachments, multiple: true, class: 'form-control' %>
  </div>
  <%end%>

  <% if current_user.can_manage_releases? %>
  <div class="form-group">
    <%= form.label :ios_impl, "Дата впровадження для iOS" %>
    <%= form.datetime_field :ios_impl, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :android_impl, "Дата впровадження для Android" %>
    <%= form.datetime_field :android_impl, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ios_release, "Дата випуску для iOS" %>
    <%= form.datetime_field :ios_release, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :android_release, "Дата випуску для Android" %>
    <%= form.datetime_field :android_release, include_blank: true, class: 'form-control' %>
  </div>

  <%end%>

  <div class="form-group">
    <%= form.submit submit_text, class: 'btn btn_primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="title_container">
  <h1>Подія</h1>
  <%= link_to 'Назад', events_path, class: 'btn btn-custom-color' %>
</div>
<%= render 'form', event: @event, event_params: @event_params, submit_text: 'Редагувати' %>

app/views/events/index.html.erb
<!-- app/views/events/index.html.erb -->

<div class="container mt-5">
  <h2>Події</h2>

  <div class="d-flex justify-content-between align-items-center mb-3">
    <!-- Пошукове поле -->
    <div class="input-group" data-controller="search">
      <%= text_field_tag :search, params[:search], id: 'search', class: 'form-control search-field', placeholder: 'Пошук за назвою або описом', data: { action: 'input->search#search', search_target: 'input' } %>
    </div>

    <!-- Кнопка "Нова Подія" -->
    <% if current_user.can_add_event? %>
      <%= link_to 'Нова Подія', new_event_path, class: 'btn btn-custom-color' %>
    <% end %>
  </div>

  <table class="table table-striped" id="events-table">
    <thead>
    <tr>
      <th>Назва</th>
      <th>Опис</th>
      <th>Категорія</th>
      <th>Впровадження</th>
      <th>Випуск в маркет</th>
      <th>Дії</th>
    </tr>
  </thead>
    <tbody data-search-target="results">
      <%= render partial: 'events_table', locals: { events: @events } %>
    </tbody>
  </table>
</div>

<%= link_to 'Назад', home_path, class: 'btn btn-link'%>

app/views/events/new.html.erb
<div class="title_container">
  <h1>Нова подія</h1>
  <%= link_to 'Назад', events_path, class: 'btn btn-custom-color' %>
</div>


<%= render 'form', event: @event, event_params: @event_params, submit_text: 'Створити' %>

app/views/events/show.html.erb
<div class="event-container" data-controller="attachment">
  <div class="event-details card mb-3">
    <div class="card-header text-white">
      <h2><%= @event.name %></h2>
    </div>
    <div class="card-body">
      <p class="card-text">
        <strong>Категорія:</strong>
        <span class="badge badge-info"><%= @event.category.name %></span>
      </p>

      <p class="card-text"><%= @event.description %></p>

      <% if @event.event_params.any? %>
        <p class="card-text"><strong>Параметри події:</strong></p>
        <ul>
          <% @event.event_params.each do |param| %>
            <li><%= param.name %> - <%= param.description %></li>
          <% end %>
        </ul>
      <% end %>

      <% if @event.attachments.attached? %>
        <div class="attachments-section" data-controller="attachment">
          <button class="expand-button btn btn-custom-color" data-action="click->attachment#toggle">Вкладення (<%= @event.attachments.count %>)</button>
          <div class="attachments-content" data-attachment-target="attachmentsContent" style="display: none;">
            <% if @event.attachments.count >= 3 %>
              <div class="attachments-slider">
                <button class="slider-nav comment-slider-prev" data-action="click->attachment#scrollAttachments" data-direction="-1">&lt;</button>
                <div class="attachments-list">
                  <% @event.attachments.each do |attachment| %>
                    <div class="attachment-item">
                      <span class="attachment-title"><%= attachment.filename.to_s %></span>
                      <% if attachment.content_type.starts_with?('image/') %>
                        <img src="<%= url_for(attachment) %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                      <% elsif attachment.content_type == 'application/pdf' %>
                        <img src="<%= asset_path('pdf-icon.svg') %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                      <% else %>
                        <img src="<%= asset_path(get_icon_for(attachment.content_type)) %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                      <% end %>
                    </div>
                  <% end %>
                </div>
                <button class="slider-nav comment-slider-next" data-action="click->attachment#scrollAttachments" data-direction="1">&gt;</button>
              </div>
            <% else %>
              <div class="attachments-list">
                <% @event.attachments.each do |attachment| %>
                  <div class="attachment-item">
                    <span class="attachment-title"><%= attachment.filename.to_s %></span>
                    <% if attachment.content_type.starts_with?('image/') %>
                      <img src="<%= url_for(attachment) %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                    <% elsif attachment.content_type == 'application/pdf' %>
                      <img src="<%= asset_path('pdf-icon.png') %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                    <% else %>
                      <img src="<%= asset_path(get_icon_for(attachment.content_type)) %>" alt="<%= attachment.filename.to_s %>" class="attachment-img" data-action="click->attachment#showModal" data-url="<%= url_for(attachment) %>" data-title="<%= attachment.filename.to_s %>" data-type="<%= attachment.content_type %>">
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="platform-dates">
        <div>
          <% if @event.ios_impl %>
            <p class="card-text">
              <i class="fa-brands fa-apple"></i> <strong>Впроваджено:</strong> <%= @event.ios_impl.strftime("%Y-%m-%d %H:%M:%S") %>
            </p>
          <% end %>
          <% if @event.ios_release %>
            <p class="card-text">
              <i class="fa-brands fa-apple"></i> <strong>Випущено в App Store:</strong> <%= @event.ios_release.strftime("%Y-%m-%d %H:%M:%S") %>
            </p>
          <% end %>
        </div>
        <div>
          <% if @event.android_impl %>
            <p class="card-text">
              <i class="fa-brands fa-android"></i> <strong>Впроваджено:</strong> <%= @event.android_impl.strftime("%Y-%m-%d %H:%M:%S") %>
            </p>
          <% end %>
          <% if @event.android_release %>
            <p class="card-text">
              <i class="fa-brands fa-android"></i> <strong>Випущено в Play Market:</strong> <%= @event.android_release.strftime("%Y-%m-%d %H:%M:%S") %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="buttons-container">
      <% if current_user.can_open_event_edit? %>
        <%= link_to '✏️', edit_event_path(@event), class: 'btn btn-custom-color btn-sm', title: 'Редагувати' %>
      <% end %>
      <% if current_user.can_delete_event? %>
        <%= link_to '🗑️', event_path(@event), data: { turbo_method: :delete, turbo_confirm: 'Ви впевнені?' }, class: 'btn btn-custom-color btn-sm', title: 'Видалити' %>
      <% end %>
    </div>
  </div>

  <div class="comments-section">
  <button class="expand-button btn btn-custom-color" data-action="click->attachment#toggleComments">Коментарі (<%= @event.comments.count %>)</button>
  <div class="comments-content" data-attachment-target="commentsContent">
    <div class="comments-slider">
      <button class="slider-nav prev" data-action="click->attachment#scrollAttachments" data-direction="-1">&#9650;</button>
      <div class="comments-list">
        <%= render @event.comments %>
      </div>
      <button class="slider-nav next" data-action="click->attachment#scrollAttachments" data-direction="1">&#9660;</button>
    </div>
    <div>
      <%= render 'comments/form', commentable: @event, comment: Comment.new %>
    </div>
  </div>
</div>
</div>