config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
  end

  resources :event_params
  resources :categories

   get 'history', to: 'history#index'

  root 'home#index', as: :home
end

app/models/event_param.rb
class EventParam < ApplicationRecord
    has_and_belongs_to_many :events
    
    validates :name, presence: true, uniqueness: { case_sensitive: true }

    has_paper_trail
end

app/controllers/event_params_controller.rb
class EventParamsController < ApplicationController
    before_action :set_event_param, only: [ :show, :edit, :update, :destroy ]
    before_action :authenticate_user!

    def index
      @event_params = EventParam.all.order(:name)
    end

    def show
    end

    def new
      @event_param = EventParam.new
    end

    def create
      @event_param = EventParam.new(event_param_params)
      if @event_param.save
        redirect_to @event_param, notice: 'Event parameter was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @event_param.update(event_param_params)
        redirect_to @event_param, notice: 'Event parameter was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @event_param.events.each do |event|
        event.event_params.delete(@event_param)
      end
      @event_param.destroy
      redirect_to event_params_url, notice: 'Event parameter was successfully destroyed.'
    end

    private

    def set_event_param
      @event_param = EventParam.find(params[:id])
    end

    def event_param_params
      params.require(:event_param).permit(:name, :description)
    end
end

app/helpers/event_params_helper.rb
module EventParamsHelper
end

app/views/event_params/_form.html.erb
<%= form_with(model: @event_param, local: true, class: 'form_container') do |form| %>
  <% if @event_param.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_param.errors.count, "error") %> prohibited this event parameter from being saved:</h2>
      <ul>
        <% @event_param.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit submit_text, class: 'btn btn_primary' %>
  </div>
<% end %>

app/views/event_params/edit.html.erb
<div class="title_container">
  <h1> Редагувати параметр</h1>
  <%= link_to 'Back', event_params_path, class: 'btn btn-custom-color' %>
</div>

<%= render 'form', event_param: @event_param, submit_text: 'Редагувати' %>

app/views/event_params/index.html.erb
<!-- app/views/event_params/index.html.erb -->

<div class="container mt-5">
  <div class="title_container">
    <h2>Параметри Подій</h2>
    <% if current_user.can_manage_event_params? %>
      <%= link_to 'Новий Параметр Події', new_event_param_path, class: 'btn btn-custom-color' %>
    <% end %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Назва</th>
        <th>Опис</th>
        <th>Дії</th>
      </tr>
    </thead>
    <tbody>
      <% @event_params.each do |event_param| %>
        <tr>
          <td><%= link_to event_param.name, event_param_path(event_param), class: 'btn-link' %></td>
          <td class="description-cell">
            <input type="checkbox" id="toggle-description-<%= event_param.id %>" class="toggle-description" />
            <label for="toggle-description-<%= event_param.id %>" class="show-more-label"></label>
            <span class="short-description">
              <%= truncate(event_param.description, length: 50) %>
            </span>
            <span class="full-description">
              <%= event_param.description %>
            </span>
          </td>
          <td>
            <%= link_to '🔍', event_param_path(event_param), class: 'btn btn-custom-color btn-sm', title: 'Показати' %>
            <% if current_user.can_manage_event_params? %>
              <%= link_to '✏️', edit_event_param_path(event_param), class: 'btn btn-custom-color btn-sm', title: 'Редагувати' %>
              <%= link_to '🗑️', event_param_path(event_param), data: { turbo_method: :delete, turbo_confirm: 'Ви впевнені?' }, class: 'btn btn-custom-color btn-sm', title: 'Видалити' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Назад', home_path, class: 'btn-link' %>

app/views/event_params/new.html.erb
<div class="title_container">
  <h1> Новий параметр</h1>
  <%= link_to 'Back', event_params_path, class: 'btn btn-custom-color' %>
</div>

<%= render 'form', event_param: @event_param, submit_text: 'Створити' %>

app/views/event_params/show.html.erb
<!-- app/views/event_params/show.html.erb -->
<div class="form_container">

  <p>
    <strong>Назва:</strong>
    <%= @event_param.name %>
  </p>

  <p>
    <strong>Опис:</strong>
    <%= @event_param.description %>
  </p>
  <div class='buttons-container'>
  <% if current_user.can_manage_event_params? %>
    <%= link_to '✏️', edit_event_param_path(@event_param), class: 'btn btn-outline-primary btn-sm', title: 'Редагувати' %>
    <%= link_to '🗑️', event_param_path(@event_param), data: { turbo_method: :delete, turbo_confirm: 'Ви впевнені?' }, class: 'btn btn-outline-primary btn-sm', title: 'Видалити' %>
  <% end %>
  </div>
</div>
<%= link_to 'Назад', event_params_path, class: 'btn-link' %>