config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
  end

  resources :event_params
  resources :categories

   get 'history', to: 'history#index'

  root 'home#index', as: :home
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events, dependent: :destroy
  validates :name, presence: true

  has_paper_trail
end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.all.order(:name)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.events.each do |event| 
      event.destroy
    end
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, class: 'form_container') do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prevented this category from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Ім'я" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit submit_text, class: 'btn btn_primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!-- app/views/categories/edit.html.erb -->
<div class="title_container">
  <h1>Редагувати категорію</h1>
  <%= link_to 'Назад', categories_path, class: 'btn btn-custom-color' %>
</div>
<%= render 'form', category: @category, submit_text: "Редагувати"%>

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->
<div class="title_container">
  <h1>Категорії</h1>
  <%= link_to 'Нова категорія', new_category_path, class: 'btn btn-custom-color' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Ім'я</th>
      <th>Дії</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to '🔍', category, class: 'btn btn-custom-color btn-sm', title: 'Показати' %>
          <% if current_user.can_manage_categories? %>
          <%= link_to '✏️', edit_category_path(category), class: 'btn btn-custom-color btn-sm', title: 'Редагувати' %>
          <%= link_to '🗑️', category_path(category), data: { turbo_method: :delete, turbo_confirm: 'Ви впевнені? Зверніть увагу що усі події цієї категорії також будуть знищені.' }, class: 'btn btn-custom-color btn-sm', title: 'Видалити' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Назад', home_path, class: 'btn btn-link' %>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->
<div class="title_container">
  <h1>Нова категорія</h1>
  <%= link_to 'Назад', categories_path, class: 'btn btn-custom-color' %>
</div>
<%= render 'form', category: @category, submit_text: "Створити" %>

app/views/categories/show.html.erb
<div class="title_container">
  <h1>Події категорії: "<%= @category.name %>"</h1>
  <%= link_to 'Back', event_params_path, class: 'btn btn-custom-color' %>
</div>
 <table class="table table-striped" id="events-table">
    <thead>
    <tr>
      <th>Назва</th>
      <th>Опис</th>
      <th>Категорія</th>
      <th>Впровадження</th>
      <th>Випуск в маркет</th>
      <th>Дії</th>
    </tr>
  </thead>
    <tbody data-search-target="results">
      <%= render partial: 'events/events_table', locals: { events: @category.events } %>
    </tbody>
  </table>